const statesAndCities = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu"],
  Adamawa: ["Yola", "Mubi", "Numan", "Jimeta"],
  AkwaIbom: ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  Bauchi: ["Bauchi", "Azare", "Jama’are", "Katagum"],
  Bayelsa: ["Yenagoa", "Ogbia", "Sagbama", "Brass"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala"],
  Borno: ["Maiduguri", "Biu", "Monguno", "Chibok"],
  CrossRiver: ["Calabar", "Ikom", "Ogoja", "Obudu"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ezza"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Igueben"],
  Ekiti: ["Ado-Ekiti", "Ikere", "Ise", "Emure"],
  Enugu: ["Enugu", "Nsukka", "Awgu", "Udi"],
  Gombe: ["Gombe", "Kaltungo", "Dukku", "Yamaltu"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Kazaure"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Sabon Gari"],
  Kano: ["Kano", "Wudil", "Rano", "Gaya"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru"],
  Kogi: ["Lokoja", "Okene", "Idah", "Kabba"],
  Kwara: ["Ilorin", "Offa", "Jebba", "Patigi"],
  Lagos: ["Ikeja", "Lekki", "Surulere", "Epe", "Ikorodu"],
  Nassarawa: ["Lafia", "Keffi", "Akwanga", "Doma"],
  Niger: ["Minna", "Bida", "Suleja", "Kontagora"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota"],
  Ondo: ["Akure", "Owo", "Ondo Town", "Ikare"],
  Osun: ["Osogbo", "Ife", "Ilesa", "Ikirun"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin"],
  Plateau: ["Jos", "Barkin Ladi", "Pankshin", "Shendam"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny", "Omoku"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Rabah"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Serti"],
  Yobe: ["Damaturu", "Potiskum", "Nguru", "Gashua"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Bungudu"],
  FCT: ["Abuja", "Garki", "Wuse", "Maitama"],
};

export default statesAndCities;
